name: okaychata
description: A basic note taking application that uses Firebase for auth and storage.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  flutter: ">=3.22.0"
  sdk: ">=3.4.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  cloud_firestore: ^4.8.4
  firebase_analytics: ^10.1.6
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  path: ^1.8.3
  google_fonts: ^5.1.0
  share_plus: ^7.1.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_native_splash: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
