// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbhKdL55orppgjP-3tqbu6yQQXFcinCQI',
    appId: '1:102007304767:android:060580bb90939af840fe8a',
    messagingSenderId: '102007304767',
    projectId: 'flutter-course-fcc',
    storageBucket: 'flutter-course-fcc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGP223UKpxqLgYBQAyJwUItL1-n9Mrn-A',
    appId: '1:102007304767:ios:fcc9066613c2114540fe8a',
    messagingSenderId: '102007304767',
    projectId: 'flutter-course-fcc',
    storageBucket: 'flutter-course-fcc.appspot.com',
    iosClientId: '102007304767-m9tfn95emv2npjt99o2qtr2qubsturls.apps.googleusercontent.com',
    iosBundleId: 'com.baalho.okaychata',
  );
}
